### ISSUE TITLE
Conflict with power-bottom

### ISSUE THREAD

**Issue by romdotdog** [cyyynthia/pronoundb-powercord#2]
[bottom-software-foundation/power-bottom](https://github.com/bottom-software-foundation/power-bottom) becomes non-functional when used in cooperation with this plugin and trying to decode a registered user of PronounDB's message. 
After a moderate amount of time debugging, I've found this line to be the cause:
https://github.com/cyyynthia/pronoundb-powercord/blob/75d9e670a068ba623c048a0d8b7c7278d5cab7ba/PronounsWrapper.js#L44
If I modified that line to `const message = i.props.message`, then both plugins would work in my limited testing.

**Comment by cyyynthia** [comment]
The idea behind this clone deep was to not pollute Discord's cache with PronounDB-related stuff (since muting the object would affect the base object, which is stored in cache), but I can see why this conflicts (since I doubt it preserves the prototype). I'll try and see if I can do it in a different way soon.
